include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - test
    - assets/translations
    - "lib/firebase_options.dart"
    - "lib/product/components/chart/chart_model.dart"

linter:
  rules:
    use_build_context_synchronously: false
    public_member_api_docs: false
    prefer_constructors_over_static_methods: false