name: finance_bank_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  kartal: ^2.7.0
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  syncfusion_flutter_charts: ^20.4.38

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/logos/
